"""Add comments relationship to Post

Revision ID: 4358f34bd93f
Revises: f36c8a75eed8
Create Date: 2024-12-13 10:32:31.858429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4358f34bd93f'
down_revision = 'f36c8a75eed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_dislikes')
    op.drop_table('comment_likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_likes',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name='comment_likes_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='comment_likes_ibfk_2'),
    sa.PrimaryKeyConstraint('user_id', 'comment_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('comment_dislikes',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name='comment_dislikes_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='comment_dislikes_ibfk_2'),
    sa.PrimaryKeyConstraint('user_id', 'comment_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
